# Generated by Django 3.1 on 2020-08-10 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('iddestino', models.AutoField(db_column='idDestino', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=300)),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'Destino',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('idviaje', models.AutoField(db_column='idViaje', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('capacidad', models.IntegerField()),
            ],
            options={
                'db_table': 'Viaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idcliente', models.OneToOneField(db_column='idCliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='viajes.cliente')),
            ],
            options={
                'db_table': 'Reserva',
                'managed': False,
            },
        ),
    ]
